/* eslint-disable */
// @ts-nocheck

/**
 * This file is auto-generated by `@tanstack/router-vite-plugin` on `vite dev`
 * and `vite build`. The hand-written stub below is committed so a clean clone
 * typechecks before Vite has run once. The plugin overwrites it on first run.
 */

import { Route as rootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRoute;
      parentRoute: typeof rootRoute;
    };
  }
}

export const routeTree = rootRoute.addChildren([IndexRoute] as const);
