/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTenantSlugRouteImport } from './routes/t.$tenantSlug'
import { Route as TTenantSlugIndexRouteImport } from './routes/t.$tenantSlug.index'
import { Route as TTenantSlugLoginRouteImport } from './routes/t.$tenantSlug.login'
import { Route as TTenantSlugAuthedRouteImport } from './routes/t.$tenantSlug._authed'
import { Route as TTenantSlugAuthedHomeRouteImport } from './routes/t.$tenantSlug._authed.home'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTenantSlugRoute = TTenantSlugRouteImport.update({
  id: '/t/$tenantSlug',
  path: '/t/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const TTenantSlugIndexRoute = TTenantSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TTenantSlugRoute,
} as any)
const TTenantSlugLoginRoute = TTenantSlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => TTenantSlugRoute,
} as any)
const TTenantSlugAuthedRoute = TTenantSlugAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => TTenantSlugRoute,
} as any)
const TTenantSlugAuthedHomeRoute = TTenantSlugAuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => TTenantSlugAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/t/$tenantSlug': typeof TTenantSlugAuthedRouteWithChildren
  '/t/$tenantSlug/login': typeof TTenantSlugLoginRoute
  '/t/$tenantSlug/': typeof TTenantSlugIndexRoute
  '/t/$tenantSlug/home': typeof TTenantSlugAuthedHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/t/$tenantSlug': typeof TTenantSlugIndexRoute
  '/t/$tenantSlug/login': typeof TTenantSlugLoginRoute
  '/t/$tenantSlug/home': typeof TTenantSlugAuthedHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/t/$tenantSlug': typeof TTenantSlugRouteWithChildren
  '/t/$tenantSlug/_authed': typeof TTenantSlugAuthedRouteWithChildren
  '/t/$tenantSlug/login': typeof TTenantSlugLoginRoute
  '/t/$tenantSlug/': typeof TTenantSlugIndexRoute
  '/t/$tenantSlug/_authed/home': typeof TTenantSlugAuthedHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/t/$tenantSlug'
    | '/t/$tenantSlug/login'
    | '/t/$tenantSlug/'
    | '/t/$tenantSlug/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/t/$tenantSlug' | '/t/$tenantSlug/login' | '/t/$tenantSlug/home'
  id:
    | '__root__'
    | '/'
    | '/t/$tenantSlug'
    | '/t/$tenantSlug/_authed'
    | '/t/$tenantSlug/login'
    | '/t/$tenantSlug/'
    | '/t/$tenantSlug/_authed/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TTenantSlugRoute: typeof TTenantSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tenantSlug': {
      id: '/t/$tenantSlug'
      path: '/t/$tenantSlug'
      fullPath: '/t/$tenantSlug'
      preLoaderRoute: typeof TTenantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tenantSlug/': {
      id: '/t/$tenantSlug/'
      path: '/'
      fullPath: '/t/$tenantSlug/'
      preLoaderRoute: typeof TTenantSlugIndexRouteImport
      parentRoute: typeof TTenantSlugRoute
    }
    '/t/$tenantSlug/login': {
      id: '/t/$tenantSlug/login'
      path: '/login'
      fullPath: '/t/$tenantSlug/login'
      preLoaderRoute: typeof TTenantSlugLoginRouteImport
      parentRoute: typeof TTenantSlugRoute
    }
    '/t/$tenantSlug/_authed': {
      id: '/t/$tenantSlug/_authed'
      path: ''
      fullPath: '/t/$tenantSlug'
      preLoaderRoute: typeof TTenantSlugAuthedRouteImport
      parentRoute: typeof TTenantSlugRoute
    }
    '/t/$tenantSlug/_authed/home': {
      id: '/t/$tenantSlug/_authed/home'
      path: '/home'
      fullPath: '/t/$tenantSlug/home'
      preLoaderRoute: typeof TTenantSlugAuthedHomeRouteImport
      parentRoute: typeof TTenantSlugAuthedRoute
    }
  }
}

interface TTenantSlugAuthedRouteChildren {
  TTenantSlugAuthedHomeRoute: typeof TTenantSlugAuthedHomeRoute
}

const TTenantSlugAuthedRouteChildren: TTenantSlugAuthedRouteChildren = {
  TTenantSlugAuthedHomeRoute: TTenantSlugAuthedHomeRoute,
}

const TTenantSlugAuthedRouteWithChildren =
  TTenantSlugAuthedRoute._addFileChildren(TTenantSlugAuthedRouteChildren)

interface TTenantSlugRouteChildren {
  TTenantSlugAuthedRoute: typeof TTenantSlugAuthedRouteWithChildren
  TTenantSlugLoginRoute: typeof TTenantSlugLoginRoute
  TTenantSlugIndexRoute: typeof TTenantSlugIndexRoute
}

const TTenantSlugRouteChildren: TTenantSlugRouteChildren = {
  TTenantSlugAuthedRoute: TTenantSlugAuthedRouteWithChildren,
  TTenantSlugLoginRoute: TTenantSlugLoginRoute,
  TTenantSlugIndexRoute: TTenantSlugIndexRoute,
}

const TTenantSlugRouteWithChildren = TTenantSlugRoute._addFileChildren(
  TTenantSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TTenantSlugRoute: TTenantSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
